# code, name, default_item
location_table = {
    "Things Betwixt": [
        (10025010, "[TB - Chest] Human Effigy", "Human Effigy"),
        (10026000, "[TB] Rusted Coin", "Rusted Coin"),
        (10026001, "[TB] Rusted Coin (2)", "Rusted Coin"),
        (10026020, "[TB] Gold Pine Resin", "Gold Pine Resin"),
        (10026030, "[TB] Small Smooth & Silky Stone", "Small Smooth & Silky Stone"),
        (10026031, "[TB] Small Smooth & Silky Stone (2)", "Small Smooth & Silky Stone"),
        (10026040, "[TB] Soul of a Nameless Soldier", "Soul of a Nameless Soldier"),
        (10026050, "[TB] Soul of a Nameless Soldier, Torch (1)", "Soul of a Nameless Soldier"),
        (10026051, "[TB] Soul of a Nameless Soldier, Torch (2)", "Torch"),
        (10026060, "[TB] Cracked Red Eye Orb", "Cracked Red Eye Orb"),
        (10026070, "[TB] Dagger", "Dagger"),
        (10026080, "[TB] Lifegem", "Lifegem"),
        (10026090, "[TB] Amber Herb", "Amber Herb"),
        (10027000, "[TB] Bone of Order", "Bone of Order"),
    ],
    "Majula": [
        (10045000, "[Majula - Chest - Maughlin] Titanite Shard", "Titanite Shard"),
        (10045001, "[Majula - Chest - Maughlin] Large Titanite Shard", "Large Titanite Shard"),
        (10045002, "[Majula - Chest - Maughlin] Moon Butterfly Shield", "Moon Butterfly Shield"),
        (10045010, "[Majula - Chest - Mansion] Titanite Shard, Torch (1)", "Titanite Shard"),
        (10045011, "[Majula - Chest - Mansion] Titanite Shard, Torch (2)", "Torch"),
        (10045020, "[Majula - Chest - Forgotten Key] Soul Vortex", "Soul Vortex"),
        (10045030, "[Majula - Chest - Forgotten Key] Great Lightning Spear", "Great Lightning Spear"),
        (10045040, "[Majula - Chest - Lenigrast] Estus Flask Shard", "Estus Flask Shard"),
        (10045050, "[Majula - Chest - Forgotten Key] Witchtree Branch, Witchtree Bellvine (1)", "Witchtree Branch"),
        (10045051, "[Majula - Chest - Forgotten Key] Witchtree Branch, Witchtree Bellvine (2)", "Witchtree Bellvine"),
        (10045060, "[Majula - Chest - Route to Forest] Rusted Coin", "Rusted Coin"),
        (10045070, "[Majula - Chest - Route to Heide] Crimson Parma", "Crimson Parma"),
        (10045500, "[Majula - Chest - Under Mansion] Rubbish", "Rubbish"),
        (10045600, "[Majula - Chest - Under Mansion] Soul Vessel", "Soul Vessel"),
        (10046000, "[Majula] Estus Flask Shard", "Estus Flask Shard"),
        (10046010, "[Majula] Divine Blessing", "Divine Blessing"),
        (10046020, "[Majula] Morning Star, Cleric's Sacred Chime (1)", "Morning Star"),
        (10046021, "[Majula] Morning Star, Cleric's Sacred Chime (2)", "Cleric's Sacred Chime"),
        (10046030, "[Majula] Binoculars", "Binoculars"),
        (10046040, "[Majula] Soul of a Nameless Soldier, Lifegem (1)", "Soul of a Nameless Soldier"),
        (10046041, "[Majula] Soul of a Nameless Soldier, Lifegem (2)", "Lifegem"),
        (10046050, "[Majula] Poison Moss", "Poison Moss"),
        (10046060, "[Majula] Pharros' Lockstone", "Pharros' Lockstone"),
        (10046070, "[Majula] Estus Flask Shard", "Estus Flask Shard"),
        (10046080, "[Majula] Rouge Water", "Rouge Water"),
        (10046090, "[Majula] Ring of the Evil Eye+1", "Ring of the Evil Eye+1"),
        (10046100, "[Majula] Pharros' Lockstone", "Pharros' Lockstone"),
        (10046110, "[Majula] Homeward Bone", "Homeward Bone"),
        (10046120, "[Majula] Lifegem", "Lifegem"),
        (10046130, "[Majula] Radiant Lifegem", "Radiant Lifegem")
    ],
    "Forest of Fallen Giants": [
        (10105010, "[FoFG - Chest - Cardinal Tower] Small Leather Shield, Repair Powder (1)", "Small Leather Shield"),
        (10105011, "[FoFG - Chest - Cardinal Tower] Small Leather Shield, Repair Powder (2)", "Repair Powder"),
        (10105020, "[FoFG - Chest - Route to Forest] Human Effigy", "Human Effigy"),
        (10105021, "[FoFG - Chest - Route to Forest] Human Effigy (2)", "Human Effigy"),
        (10105030, "[FoFG - Chest - Ballista Soldier Room] Life Ring, Large Titanite Shard (1)", "Life Ring"),
        (10105031, "[FoFG - Chest - Ballista Soldier Room] Life Ring, Large Titanite Shard (2)", "Large Titanite Shard"),
        (10105040, "[FoFG - Chest - Ballista Trap Room] Titanite Shard", "Titanite Shard"),
        (10105041, "[FoFG - Chest - Ballista Trap Room] Titanite Chunk", "Titanite Chunk"),
        (10105050, "[FoFG - Chest - Under Cardinal Tower] Large Titanite Shard, Torch (1)", "Large Titanite Shard"),
        (10105051, "[FoFG - Chest - Under Cardinal Tower] Large Titanite Shard, Torch (2)", "Torch"),
        (10105070, "[FoFG - Chest - Cardinal Tower] Small White Sign Soapstone, Radiant Lifegem (1)", "Small White Sign Soapstone"),
        (10105071, "[FoFG - Chest - Cardinal Tower] Small White Sign Soapstone, Radiant Lifegem (2)", "Radiant Lifegem"),
        (10105080, "[FoFG - Chest - Pharros Lockstone Room] Chloranthy Ring", "Chloranthy Ring"),
        (10105090, "[FoFG - Chest - Pharros Lockstone Room] Large Titanite Shard", "Large Titanite Shard"),
        (10105100, "[FoFG - Chest - Overlook Firebomb Room] Mail Breaker, Infantry Helm (1)", "Mail Breaker"),
        (10105101, "[FoFG - Chest - Overlook Firebomb Room] Mail Breaker, Infantry Helm (2)", "Infantry Helm"),
        (10105110, "[FoFG - Chest - Fire Pit] Flame Quartz Ring+1", "Flame Quartz Ring+1"),
        (10105120, "[FoFG - Chest - Soldier's Rest] Large Soul of a Proud Knight, Hunter's Set (1)", "Large Soul of a Proud Knight"),
        (10105121, "[FoFG - Chest - Soldier's Rest] Large Soul of a Proud Knight, Hunter's Set (2)", "Hunter's Hat"),
        (10105121, "[FoFG - Chest - Soldier's Rest] Large Soul of a Proud Knight, Hunter's Set (3)", "Leather Armor"),
        (10105121, "[FoFG - Chest - Soldier's Rest] Large Soul of a Proud Knight, Hunter's Set (4)", "Leather Gloves"),
        (10105121, "[FoFG - Chest - Soldier's Rest] Large Soul of a Proud Knight, Hunter's Set (5)", "Leather Boots"),
        (10105130, "[FoFG - Chest - Flame Lizard Trap Room] Yearn", "Yearn"),
        (10105140, "[FoFG - Chest - Pate's Trap Passage] Sorcerer's Staff, Amber Herb (1)", "Sorcerer's Staff"),
        (10105141, "[FoFG - Chest - Pate's Trap Passage] Sorcerer's Staff, Amber Herb (2)", "Amber Herb"),
        (10106000, "[FoFG] Soul of a Lost Undead", "Soul of a Lost Undead"),
        (10106010, "[FoFG] Soul of a Nameless Soldier, Cracked Red Eye Orb (1)", "Soul of a Nameless Soldier"),
        (10106011, "[FoFG] Soul of a Nameless Soldier, Cracked Red Eye Orb (2)", "Cracked Red Eye Orb"),
        (10106020, "[FoFG] Lifegem", "Lifegem"),
        (10106030, "[FoFG] Amber Herb", "Amber Herb"),
        (10106050, "[FoFG] Divine Blessing", "Divine Blessing"),
        (10106060, "[FoFG] Wood Bolt", "Wood Bolt"),
        (10106061, "[FoFG] Heavy Bolt", "Heavy Bolt"),
        (10106070, "[FoFG] Black Firebomb, Homeward Bone (1)", "Black Firebomb"),
        (10106071, "[FoFG] Black Firebomb, Homeward Bone (2)", "Homeward Bone"),
        (10106080, "[FoFG] Torch", "Torch"),
        (10106090, "[FoFG] Lifegem, Homeward Bone (1)", "Lifegem"),
        (10106091, "[FoFG] Lifegem, Homeward Bone (2)", "Homeward Bone"),
        (10106100, "[FoFG] Halberd, Soul of a Nameless Soldier (1)", "Halberd"),
        (10106101, "[FoFG] Halberd, Soul of a Nameless Soldier (2)", "Soul of a Nameless Soldier"),
        (10106110, "[FoFG] Homeward Bone, Soul of a Lost Undead (1)", "Homeward Bone"),
        (10106111, "[FoFG] Homeward Bone, Soul of a Lost Undead (2)", "Soul of a Lost Undead"),
        (10106120, "[FoFG] Human Effigy", "Human Effigy"),
        (10106130, "[FoFG] Titanite Shard", "Titanite Shard"),
        (10106140, "[FoFG] Buckler", "Buckler"),
        (10106150, "[FoFG] Human Effigy (2)", "Human Effigy"),
        (10106160, "[FoFG] Aromatic Ooze", "Aromatic Ooze"),
        (10106170, "[FoFG] Soul of a Nameless Soldier, Throwing Knife (1)", "Soul of a Nameless Soldier"),
        (10106171, "[FoFG] Soul of a Nameless Soldier, Throwing Knife (2)", "Throwing Knife"),
        (10106180, "[FoFG] Green Blossom", "Green Blossom"),
        (10106190, "[FoFG] Large Soul of a Lost Undead", "Large Soul of a Lost Undead"),
        (10106200, "[FoFG] Shortsword, Soul of a Lost Undead (1)", "Shortsword"),
        (10106201, "[FoFG] Shortsword, Soul of a Lost Undead (2)", "Soul of a Lost Undead"),
        (10106210, "[FoFG] Soul of a Lost Undead, Torch (1)", "Soul of a Lost Undead"),
        (10106211, "[FoFG] Soul of a Lost Undead, Torch (2)", "Torch"),
        (10106220, "[FoFG] Light Crossbow", "Light Crossbow"),
        (10106230, "[FoFG] Broken Straight Sword", "Broken Straight Sword"),
        (10106240, "[FoFG] Torch (2)", "Torch"),
        (10106250, "[FoFG] Large Leather Shield, Lifegem (1)", "Large Leather Shield"),
        (10106251, "[FoFG] Large Leather Shield, Lifegem (2)", "Lifegem"),
        (10106260, "[FoFG] Human Effigy (3)", "Human Effigy"),
        (10106270, "[FoFG] Human Effigy (4)", "Human Effigy"),
        (10106280, "[FoFG] Lifegem (2)", "Lifegem"),
        (10106290, "[FoFG] Drangleic Sword, Drangleic Shield, Drangleic Mail, Drangleic Gauntlets, Drangleic Leggings (1)", "Drangleic Sword"),
        (10106291, "[FoFG] Drangleic Sword, Drangleic Shield, Drangleic Mail, Drangleic Gauntlets, Drangleic Leggings (2)", "Drangleic Shield"),
        (10106292, "[FoFG] Drangleic Sword, Drangleic Shield, Drangleic Mail, Drangleic Gauntlets, Drangleic Leggings (3)", "Drangleic Mail"),
        (10106293, "[FoFG] Drangleic Sword, Drangleic Shield, Drangleic Mail, Drangleic Gauntlets, Drangleic Leggings (4)", "Drangleic Gauntlets"),
        (10106294, "[FoFG] Drangleic Sword, Drangleic Shield, Drangleic Mail, Drangleic Gauntlets, Drangleic Leggings (5)", "Drangleic Leggings"),
        (10106300, "[FoFG] Soul of a Lost Undead (2)", "Soul of a Lost Undead"),
        (10106310, "[FoFG] Foot Soldier Shield", "Foot Soldier Shield"),
        (10106320, "[FoFG] Amber Herb (2)", "Amber Herb"),
        (10106321, "[FoFG] Wilted Dusk Herb", "Wilted Dusk Herb"),
        (10106340, "[FoFG] Soul of a Proud Knight", "Soul of a Proud Knight"),
        (10106350, "[FoFG] Cracked Red Eye Orb", "Cracked Red Eye Orb"),
        (10106360, "[FoFG] Rebel's Greatshield", "Rebel's Greatshield"),
        (10106370, "[FoFG] Soul of a Nameless Soldier, Lifegem (1)", "Soul of a Nameless Soldier"),
        (10106371, "[FoFG] Soul of a Nameless Soldier, Lifegem (2)", "Lifegem"),
        (10106371, "[FoFG] Large Soul of a Proud Knight, Old Radiant Lifegem (1)", "Large Soul of a Proud Knight"),
        (10106372, "[FoFG] Large Soul of a Proud Knight, Old Radiant Lifegem (2)", "Old Radiant Lifegem"),
        (10106380, "[FoFG] Soul of a Nameless Soldier", "Soul of a Nameless Soldier"),
        (10106390, "[FoFG] Witching Urn", "Witching Urn"),
        (10106400, "[FoFG] Lifegem (3)", "Lifegem"),
        (10106410, "[FoFG] Fire Arrow", "Fire Arrow"),
        (10106420, "[FoFG] Twinkling Titanite, Fragrant Branch of Yore (1)", "Twinkling Titanite"),
        (10106421, "[FoFG] Twinkling Titanite, Fragrant Branch of Yore (2)", "Fragrant Branch of Yore"),
        (10106430, "[FoFG] Amber Herb, Green Blossom (1)", "Amber Herb"),
        (10106431, "[FoFG] Amber Herb, Green Blossom (2)", "Green Blossom"),
        (10106440, "[FoFG] Great Soul Arrow", "Great Soul Arrow"),
        (10106450, "[FoFG] Large Soul of a Lost Undead, Blue Wooden Shield (1)", "Large Soul of a Lost Undead"),
        (10106451, "[FoFG] Large Soul of a Lost Undead, Blue Wooden Shield (2)", "Blue Wooden Shield"),
        (10106460, "[FoFG] Firedrake Stone", "Firedrake Stone"),
        (10106470, "[FoFG] Hawk Ring", "Hawk Ring"),
        (10106480, "[FoFG] Large Soul of a Proud Knight", "Large Soul of a Proud Knight"),
        (10106490, "[FoFG] Dried Fingers, Radiant Lifegem (1)", "Dried Fingers"),
        (10106491, "[FoFG] Dried Fingers, Radiant Lifegem (2)", "Radiant Lifegem"),
        (10106500, "[FoFG] Soul of a Nameless Soldier, Torch (1)", "Soul of a Nameless Soldier"),
        (10106501, "[FoFG] Soul of a Nameless Soldier, Torch (2)", "Torch"),
    ]
}